In [1]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [6]:
# Importing the dataset

df=pd.read_csv("data/cracow_apartments.csv")
print(df.head())
print(df.shape)




   distance_to_city_center  rooms   size    price
0                      2.4    1.0  19.35  191.565
1                      2.4    2.0  13.08  221.568
2                      5.0    1.0  24.66  185.936
3                      1.9    1.0  24.82  275.502
4                      1.9    1.0  25.39  241.205
(76, 4)


In [7]:
print(df.isnull().sum())

distance_to_city_center    0
rooms                      0
size                       0
price                      0
dtype: int64


In [9]:
# Defining X and Y
X =df.iloc[:,0:3].values # All rows and 0 to 3 columns
y =df.iloc[:,3].values # all rows and only 3rd-column
print(X)
print("Printing Y")
print(y)


[[  2.4    1.    19.35]
 [  2.4    2.    13.08]
 [  5.     1.    24.66]
 [  1.9    1.    24.82]
 [  1.9    1.    25.39]
 [  5.9    1.    25.54]
 [  3.     1.    25.62]
 [  9.     1.    26.04]
 [  8.4    1.    26.26]
 [  8.4    1.    26.26]
 [  2.5    1.    26.6 ]
 [  6.7    1.    26.87]
 [  8.5    1.    27.85]
 [  2.4    2.    27.86]
 [  3.4    1.    27.93]
 [  2.3    1.    28.32]
 [  1.4    3.    29.  ]
 [  2.     1.    29.91]
 [  1.9    2.    30.83]
 [  6.3    2.    31.68]
 [  5.9    2.    32.02]
 [  7.4    2.    32.22]
 [  2.7    2.    34.32]
 [  7.4    2.    34.32]
 [  4.     2.    34.78]
 [  7.6    2.    35.01]
 [  7.1    2.    37.11]
 [  4.9    2.    37.41]
 [  5.5    2.    38.7 ]
 [  1.5    3.    29.  ]
 [  8.7    3.    45.15]
 [  2.5    3.    48.17]
 [  9.     3.    48.52]
 [  6.4    3.    49.42]
 [  5.7    3.    49.44]
 [  3.8    3.    50.91]
 [  7.6    3.    51.9 ]
 [  4.1    3.    52.4 ]
 [  3.4    3.    52.7 ]
 [  4.7    3.    53.61]
 [  7.4    3.    53.83]
 [  7.4    3.   

In [21]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

# Importing the model
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

#Fitting the model
lr.fit(X_train,y_train)

#Predict
y_pred =lr.predict(X_test)
print("Predicted values :",lr.score(X_train,y_train))
print("Training data score :",lr.score(X_test,y_test))

# Model Evaluation
from sklearn import metrics
rmse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
R2 = metrics.r2_score(y_test,y_pred)
print("RMSE Score :",rmse)
print("R2_Score :",R2)



Predicted values : 0.9480633896446401
Training data score : 0.9369931160084563
RMSE Score : 33.43412011901929
R2_Score : 0.9369931160084563


In [25]:
# Predicting by giving the own values
print("predicted price :")
print(lr.predict([[2.5,3,32.5]]))

# Try for new values
print("predicted price for new values input by you :")
print(lr.predict([[1.5,2,36]]))

predicted price :
[284.9225274]
predicted price for new values input by you :
[351.08925617]


In [33]:
# Saving a model using pickel

import pickle
with open("model_pickle","wb") as f:
    pickle.dump(lr,f)

In [34]:
# Saving a model using Joblib

import joblib
joblib.dump(lr,"model_joblib")

['model_joblib']